In [1]:
import pyro

In [2]:
import torch

In [3]:
true_coefs = torch.tensor([1., 2., 3.])

In [4]:
data = torch.randn(2000, 3)

In [6]:
dim = 3

In [7]:
import pyro.distributions as dist

In [32]:
labels = dist.Bernoulli(logits=(true_coefs * data).sum(-1)).sample()

In [13]:
((true_coefs * data).sum(-1)).shape

torch.Size([2000])

In [15]:
coefs_mean = torch.zeros(dim)
coefs_mean

tensor([0., 0., 0.])

In [16]:
coefs = pyro.sample('beta', dist.Normal(coefs_mean, torch.ones(3)))


In [18]:
coefs # random coeffs sampled from beta distr

tensor([-0.6415, -1.2336, -0.6235])

In [19]:
y = pyro.sample('y', dist.Bernoulli(logits=(coefs * data).sum(-1)), obs=labels)

/home/rka/.local/lib/python3.10/site-packages/pyro/primitives.py:163: RuntimeWarning: trying to observe a value outside of inference at y
  warnings.warn(


In [23]:
y[1:100]

tensor([0., 0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 1., 1., 1., 0., 1., 0.,
        1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 1., 0.,
        0., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 1., 1., 1., 0., 1., 0.,
        1., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 1., 1., 0., 1., 1., 1.,
        1., 0., 1., 0., 0., 1., 1., 1., 0., 1., 0., 0., 1., 0., 1., 1., 1., 0.,
        0., 1., 0., 0., 1., 0., 1., 1., 0.])

In [26]:
labels[1:100]

tensor([0., 0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 1., 1., 1., 0., 1., 0.,
        1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 1., 0.,
        0., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 1., 1., 1., 0., 1., 0.,
        1., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 1., 1., 0., 1., 1., 1.,
        1., 0., 1., 0., 0., 1., 1., 1., 0., 1., 0., 0., 1., 0., 1., 1., 1., 0.,
        0., 1., 0., 0., 1., 0., 1., 1., 0.])

In [33]:
(labels == y).sum()

tensor(1634)

In [28]:
y.shape

torch.Size([2000])